name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:

  standard:

    strategy:

      fail-fast: false

      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        shell: bash -l {0}

    name: "${{ matrix.runs-on }} • x64 ${{ matrix.args }}"
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Install mamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml

    # - name: Set conda environment "test"
    #   uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     mamba-version: "*"
    #     channels: conda-forge,defaults
    #     channel-priority: true
    #     environment-file: environment.yaml
    #     activate-environment: test
    #     auto-activate-base: false

    - name: Configure using CMake
      if: runner.os != 'Windows'
      run: cmake -Bbuild -DBUILD_TESTS=1 -DBUILD_EXAMPLES=1 -DCMAKE_CONFIGURATION_TYPES=Release

    - name: Configure using CMake
      if: runner.os == 'Windows'
      run: |
        conda install -c conda-forge clang_win-64 ninja
        cmake -Bbuild -DBUILD_TESTS=1 -DBUILD_EXAMPLES=1 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Build tests & examples
      working-directory: build
      run: cmake --build .

    - name: Run tests & examples
      working-directory: build
      run: ctest -C Debug --output-on-failure
